### ISSUE TITLE
Dependências não instaladas

### ISSUE THREAD

**Issue by caioiglesias** [Bleez/Bleez-Correios#2]
```
2016/11/04 03:14:36 [error] 15338#15338: *2533 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'PhpQuery\PhpQuery' not found in /usr/share/nginx/html/magento2/vendor/bleez/correios/Model/Endereco/Correios.php:30
Stack trace:
#0 /usr/share/nginx/html/magento2/vendor/bleez/correios/Model/Consulta.php(90): Bleez\Correios\Model\Endereco\Correios::getEndereco(4076010)
#1 [internal function]: Bleez\Correios\Model\Consulta->consultaCep(4076010)
#2 /usr/share/nginx/html/magento2/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#3 /usr/share/nginx/html/magento2/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#4 /usr/share/nginx/html/magento2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /usr/share/nginx/html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\H" while reading response header from upstream, client: 189.34.175.250, server: , request: "GET /rest/V1/consultaCep/04076010?_=1478229253994 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "x.x.x.x", referrer: "http://x.x.x.x/checkout/"
```

Nenhuma das dependências foi instalada com o comando de instalação do composer. Como é a primeira vez que uso o composer, fiquei na dúvida se falta algum argumento para que ele instale todas as dependências por conta própria.

**Comment by caioiglesias** [comment]
Ah... A versão do composer é a 0.0.1, e a do github 0.0.2.

Está sem as dependências mesmo.
