### ISSUE TITLE
Erro ao simular frete

### ISSUE THREAD

**Issue by mscampos92** [Bleez/Bleez-Correios#23]
Vi que existe um issue porém no meu caso o problema não é no SOAP, esse é o log

[2017-07-14 04:32:44] main.CRITICAL: exception 'Exception' with message 'Report ID: webapi-5968496cd0ab8; Message: Não foi possivel calcular frete.' in 
D:\xampp\htdocs\magento2\vendor\magento\framework\Webapi\ErrorProcessor.php:194
Stack trace:
#0 D:\xampp\htdocs\magento2\vendor\magento\framework\Webapi\ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 D:\xampp\htdocs\magento2\vendor\magento\module-webapi\Controller\Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 D:\xampp\htdocs\magento2\var\generation\Magento\Webapi\Controller\Rest\Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 D:\xampp\htdocs\magento2\vendor\magento\framework\App\Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 D:\xampp\htdocs\magento2\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 D:\xampp\htdocs\magento2\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

Utilizava o pedroTeixeira mas estou pensando em atualizar o magento para 2.0.X
alguma luz?

**Comment by rcicero** [comment]
Eu tive o mesmo erro e os passos para resolver foram:

1 - Revise o peso, largura, altura e comprimento dos produtos
2 - Revise o seu endereço de envio, coloque o CEP e todas as outras informações.
3 - Altere o arquivo vendor/bleez/correios/Model/Carrier/Correios.php linha 350

```
de: return number_format($shipWeight, 2);
para: return number_format($shipWeight, 1);
```

4 - Limpe Cache!!!!

**Comment by ggbellotti** [comment]
@rcicero No meu caso acontece esse erro apenas com alguns CEPs....
Tentei fazer o ultimo passo (alterar o return), porém não deu certo.
Sabe de outro meio para arrumar?

Meu erro:
[2017-09-21 14:28:30] main.CRITICAL: exception 'Exception' with message 'Não foi possivel calcular frete.' in **/public_html/vendor/bleez/correios/Model/Consulta.php:172
Stack trace:
#0 [internal function]: Bleez\Correios\Model\Consulta->estimarFrete()
#1 **/public_html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#2 **/public_html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#3 **/public_html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#4 **/public_html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#5 **/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#6 **/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#7 {main}

**Comment by albertobraschi** [comment]
estou com um erro na simulação de frete.
alguns produtos, não todos, ja tem as medidas mas ao simular ele não pega esses dados.
eu ate pus um log toda vez que simula e la fica tudo zerado.
alguem sabe o que pode estar errado?
ja reindexei e dei um flush no cache mas o problema persiste.
magento 2.1.2

**Comment by rafaelaco** [comment]
No meu caso foi apenas o peso. Deixei como kg, depois preenchi o peso de todos produtos e funcionou.
