### ISSUE TITLE
Magento 2.1

### ISSUE THREAD

**Issue by Maurodev** [Bleez/Bleez-Correios#8]
Este modulo consegue ser incluso no magento 2.1 ? pois estou tentando a integração e nao esta nem conseguir requerir o modulo Bleez_Correios...

**Comment by tcesarpinho** [comment]
Funciona sim. o erro ocorre no composer?

**Comment by felipealvarenga** [comment]
Tive o mesmo erro na instalação via composer
root@magentoxxx:/var/www/html/magento# php bin/magento module:enable --clear-static-content Bleez_Correios
Unknown module(s): 'Bleez_Correios'

**Comment by isanat** [comment]
Sabe me dizer se funciona bem na versão 2.1.5?

Porque esta dando este erro aqui.

An error occurred during execution; please try again later.

Additional information:

RuntimeException

File:
/home/wwwnacal/public_html/setup/src/Magento/Setup/Model/PackagesData.php:88
Message:
Couldn't get available versions for package bleez/correios
Stack trace:
#0 /home/wwwnacal/public_html/setup/src/Magento/Setup/Controller/ComponentGrid.php(98): Magento\Setup\Model\PackagesData->syncPackagesData()
#1 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
#2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /home/wwwnacal/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /home/wwwnacal/public_html/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /home/wwwnacal/public_html/setup/index.php(31): Zend\Mvc\Application->run()
#12 {main}

**Comment by isanat** [comment]
Como faz para desinstalar este modulo? pq não estou conseguindo fazer funcionar e nem desinstalar. obrigado

**Comment by ashishraj-cipl** [comment]
I have got the same error.
Steps to reproduce:
1) Login to magento 2 admin panel
2) Click on system > Web Setup Wizard > Component Manager

RuntimeException

File:

   ../setup/src/Magento/Setup/Model/PackagesData.php:88

Message:

    Couldn't get available versions for package bleez/correios

Stack trace:

    #0 ../setup/src/Magento/Setup/Controller/ComponentGrid.php(98): Magento\Setup\Model\PackagesData->syncPackagesData()
    #1 /mnt/vhosts/vindameecomm/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
    #2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #3 ../vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #4 ../vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #5 ../vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #6 ../vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #8 ../vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #9 ../vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #10 ../vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #11 ../setup/index.php(31): Zend\Mvc\Application->run()
    #12 {main}
